version: 1.1.{build}
build:
  verbosity: minimal
  project: Build\Automation.proj
assembly_info:
  patch: true
  file: LibTessDotNet\Properties\AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
skip_tags: true
after_test:
- call Build\PackageCurrentBranch.bat
artifacts:
- path: Build\LibTessDotNet*.zip
  name: LibTessDotNet
